# Generated by Django 5.1.2 on 2026-01-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rezervacija',
            fields=[
                ('idRezervacije', models.BigAutoField(db_column='idRezervacije', primary_key=True, serialize=False)),
                ('idVlasnik', models.BigIntegerField(db_column='idVlasnik')),
                ('idSetac', models.BigIntegerField(db_column='idSetac')),
                ('idPsa', models.BigIntegerField(db_column='idPsa')),
                ('potvrdeno', models.BooleanField(blank=True, db_column='potvrdeno', null=True)),
                ('odradena', models.BooleanField(blank=True, db_column='odradena', null=True)),
            ],
            options={
                'db_table': '"Rezervacija"',
                'managed': False,
            },
        ),
    ]
