# Generated by Django 5.1.2 on 2026-01-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pas',
            fields=[
                ('idPsa', models.BigAutoField(db_column='idPsa', primary_key=True, serialize=False)),
                ('energijaPsa', models.CharField(blank=True, db_column='energijaPsa', max_length=20, null=True)),
                ('zdravPas', models.CharField(blank=True, db_column='zdravPas', max_length=20, null=True)),
                ('posPsa', models.CharField(blank=True, db_column='posPsa', max_length=20, null=True)),
                ('socPsa', models.CharField(blank=True, db_column='socPsa', max_length=20, null=True)),
                ('imePsa', models.CharField(blank=True, db_column='imePsa', max_length=20, null=True)),
                ('starostPsa', models.BigIntegerField(blank=True, db_column='starostPsa', null=True)),
                ('pasminaPsa', models.CharField(blank=True, db_column='pasminaPsa', max_length=20, null=True)),
            ],
            options={
                'db_table': '"Pas"',
                'managed': False,
            },
        ),
    ]
