# Generated by Django 5.1.2 on 2026-01-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_membership_subscription_and_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipsubscription",
            name="valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
