openapi: 3.0.3
info:
  title: PawPal API
  version: 1.0.0
  description: 'Auth endpoints: register, login, logout, me, csrf.'
paths:
  /api/auth/csrf/:
    get:
      operationId: api_auth_csrf_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          description: CSRF token
  /api/auth/google/login-url/:
    get:
      operationId: api_auth_google_login_url_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          description: Google login URL
  /api/auth/login/:
    post:
      operationId: api_auth_login_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
            examples:
              LoginExample:
                value:
                  email: test@example.com
                  password: tajna123
                summary: Login example
        required: true
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          description: Logged in.
        '401':
          description: Invalid credentials.
        '400':
          description: Validation error.
  /api/auth/logout/:
    post:
      operationId: api_auth_logout_create
      tags:
      - api
      security:
      - cookieAuth: []
      responses:
        '200':
          description: Logged out.
  /api/auth/me/:
    get:
      operationId: api_auth_me_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          description: Current user info
  /api/auth/register/:
    post:
      operationId: api_auth_register_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
            examples:
              RegisterExample:
                value:
                  email: test@example.com
                  first_name: Test
                  last_name: User
                  password: tajna123
                  is_walker: true
                summary: Register example
        required: true
      security:
      - cookieAuth: []
      - {}
      responses:
        '201':
          description: Registered successfully.
        '400':
          description: Validation error.
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    Login:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          writeOnly: true
      required:
      - email
      - password
    Register:
      type: object
      properties:
        email:
          type: string
          format: email
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        password:
          type: string
          writeOnly: true
          minLength: 8
        is_walker:
          type: boolean
          default: false
      required:
      - email
      - first_name
      - last_name
      - password
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
