# Generated by Django 5.1.2 on 2026-01-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setnja',
            fields=[
                ('idSetnje', models.BigAutoField(db_column='idSetnje', primary_key=True, serialize=False)),
                ('terminSetnje', models.DateTimeField(blank=True, db_column='terminSetnje', null=True)),
                ('idSetac', models.BigIntegerField(db_column='idSetac')),
                ('tipSetnje', models.BigIntegerField(blank=True, db_column='tipSetnje', null=True)),
                ('cijenaSetnje', models.BigIntegerField(blank=True, db_column='cijenaSetnje', null=True)),
                ('trajanjeSetnje', models.DurationField(blank=True, db_column='trajanjeSetnje', null=True)),
            ],
            options={
                'db_table': '"Setnja"',
                'managed': False,
            },
        ),
    ]
