
--
-- Name: Admin; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Admin" (
    "idAdmin" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "passwordAdmin" character varying(50),
    "emailAdmin" character varying(50) NOT NULL,
    "usernameAdmin" character varying(50) NOT NULL
);


--
-- Name: Clanarina; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Clanarina" (
    id SERIAL PRIMARY KEY,
    iznos NUMERIC(8,2) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);


--
-- Name: Pas; Type: TABLE; Schema: public; Owner: -
--

--
-- Name: PlacanjeSetnje; Type: TABLE; Schema: public; Owner: -
--


--
-- Name: Pretplata; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Pretplata" (
    "idSetaca" bigint NOT NULL,
    "idPretplate" bigint NOT NULL
);


--
-- Name: Recenzija; Type: TABLE; Schema: public; Owner: -
--


--
-- Name: Rezervacija; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Rezervacija" (
    "idRezervacije" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "idVlasnik" bigint NOT NULL,
    "idSetac" bigint NOT NULL,
    "idPsa" bigint NOT NULL,
    potvrdeno boolean,
    odradena boolean
);


--
-- Name: Setac; Type: TABLE; Schema: public; Owner: -
--




--
-- Name: Setnja; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Setnja" (
    "idSetnje" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "terminSetnje" timestamp,
    "idSetac" bigint NOT NULL,
    "tipSetnje" bigint,
    "cijenaSetnje" bigint,
    "trajanjeSetnje" interval,
    "gradSetnje" character varying(15)
);

