
--
-- Name: Admin; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Admin" (
    "idAdmin" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "passwordAdmin" character varying(50),
    "emailAdmin" character varying(50) NOT NULL,
    "usernameAdmin" character varying(50) NOT NULL
);


--
-- Name: Clanarina; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Clanarina" (
    id SERIAL PRIMARY KEY,
    iznos NUMERIC(8,2) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);


--
-- Name: Pas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Pas" (
    "idPsa" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "idVlasnik" bigint NOT NULL,
    "energijaPsa" character varying(20),
    "zdravPas" character varying(20),
    "posPsa" character varying(20),
    "socPsa" character varying(20),
    "imePsa" character varying(20),
    "starostPsa" bigint,
    "pasminaPsa" character varying(20)
);


--
-- Name: PlacanjeSetnje; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."PlacanjeSetnje" (
    "idPlacanja" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tipPlacanja" bigint,
    "cijenaSetnje" bigint,
    "idRezervacije" bigint NOT NULL,
    "idVlasnik" bigint NOT NULL,
    "idSetac" bigint NOT NULL
);


--
-- Name: Pretplata; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Pretplata" (
    "idSetaca" bigint NOT NULL,
    "idPretplate" bigint NOT NULL
);


--
-- Name: Recenzija; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Recenzija" (
    "idRecenzije" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ocjena bigint,
    komentar character varying(50),
    "idSetac" bigint NOT NULL,
    "idVlasnik" bigint NOT NULL,
    "fotoKomentar" bigint
);


--
-- Name: Rezervacija; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Rezervacija" (
    "idRezervacije" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "idVlasnik" bigint NOT NULL,
    "idSetac" bigint NOT NULL,
    "idPsa" bigint NOT NULL,
    "gradSetnje" character varying(15),
    potvrdeno boolean,
    odradena boolean
);


--
-- Name: Setac; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Setac" (
    "idSetac" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "avgOcjena" numeric(3,2),
    "imeSetac" character varying(20),
    "prezimeSetac" character varying(20),
    "telefonSetac" character varying(15),
    "usernameSetac" character varying(20) NOT NULL,
    "emailSetac" character varying(50) NOT NULL,
    "datRegSetac" date,
    "idProfilne" bigint
);


--
-- Name: Setnja; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Setnja" (
    "idSetnje" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "terminSetnje" timestamp,
    "idSetac" bigint NOT NULL,
    "tipSetnje" bigint,
    "cijenaSetnje" bigint,
    "trajanjeSetnje" interval,
    "gradSetnje" character varying(15)
);


--
-- Name: Vlasnik; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Vlasnik" (
    "idVlasnik" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "emailVlasnik" character varying(50) NOT NULL,
    "telefonVlasnik" character varying(15),
    "idPretplate" bigint,
    "imeVlasnik" character varying(20),
    "prezimeVlasnik" character varying(20)
);




--
-- Name: Pas Pas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public."Pas"
  ADD CONSTRAINT pas_vlasnik_fk FOREIGN KEY ("idVlasnik")
  REFERENCES public."Vlasnik" ("idVlasnik")
  ON DELETE CASCADE;



--
-- Name: PlacanjeSetnje PlacanjeSetnje_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public."PlacanjeSetnje"
  ADD CONSTRAINT pay_rez_fk FOREIGN KEY ("idRezervacije") REFERENCES public."Rezervacija" ("idRezervacije") ON DELETE CASCADE;
ALTER TABLE public."PlacanjeSetnje"
  ADD CONSTRAINT pay_vlasnik_fk FOREIGN KEY ("idVlasnik") REFERENCES public."Vlasnik" ("idVlasnik");
ALTER TABLE public."PlacanjeSetnje"
  ADD CONSTRAINT pay_setac_fk FOREIGN KEY ("idSetac") REFERENCES public."Setac" ("idSetac");

--
-- Name: Pretplata Pretplata_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE  public."Pretplata"
    ADD CONSTRAINT "Pretplata_pkey" PRIMARY KEY ("idSetaca", "idPretplate");


--
-- Name: Recenzija Recenzija_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public."Recenzija"
  ADD CONSTRAINT rec_setac_fk FOREIGN KEY ("idSetac") REFERENCES public."Setac" ("idSetac");
ALTER TABLE public."Recenzija"
  ADD CONSTRAINT rec_vlasnik_fk FOREIGN KEY ("idVlasnik") REFERENCES public."Vlasnik" ("idVlasnik");
--
-- Name: Rezervacija Rezervacija_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public."Rezervacija"
  ADD CONSTRAINT rez_vlasnik_fk FOREIGN KEY ("idVlasnik") REFERENCES public."Vlasnik" ("idVlasnik");
ALTER TABLE public."Rezervacija"
  ADD CONSTRAINT rez_setac_fk FOREIGN KEY ("idSetac") REFERENCES public."Setac" ("idSetac");
ALTER TABLE public."Rezervacija"
  ADD CONSTRAINT rez_pas_fk FOREIGN KEY ("idPsa") REFERENCES public."Pas" ("idPsa");





ALTER TABLE public."Setac" ADD CONSTRAINT setac_email_unique UNIQUE ("emailSetac");
ALTER TABLE public."Setac" ADD CONSTRAINT setac_username_unique UNIQUE ("usernameSetac");
ALTER TABLE public."Setac" ADD CONSTRAINT setac_phone_unique UNIQUE ("telefonSetac");


--
-- Name: Setnja Setnja_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public."Setnja"
  ADD CONSTRAINT setnja_setac_fk FOREIGN KEY ("idSetac") REFERENCES public."Setac" ("idSetac");



ALTER TABLE  public."Vlasnik"
    ADD CONSTRAINT "Vlasnik_email_unique" UNIQUE ("emailVlasnik");


--
-- PostgreSQL database dump complete
--

