# Generated by Django 5.1.2 on 2026-01-15 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Setac",
            fields=[
                (
                    "idSetac",
                    models.BigAutoField(
                        db_column="idSetac", primary_key=True, serialize=False
                    ),
                ),
                (
                    "avgOcjena",
                    models.DecimalField(
                        blank=True,
                        db_column="avgOcjena",
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "imeSetac",
                    models.CharField(
                        blank=True, db_column="imeSetac", max_length=20, null=True
                    ),
                ),
                (
                    "prezimeSetac",
                    models.CharField(
                        blank=True, db_column="prezimeSetac", max_length=20, null=True
                    ),
                ),
                (
                    "telefonSetac",
                    models.CharField(
                        blank=True, db_column="telefonSetac", max_length=15, null=True
                    ),
                ),
                (
                    "usernameSetac",
                    models.CharField(db_column="usernameSetac", max_length=20),
                ),
                ("emailSetac", models.CharField(db_column="emailSetac", max_length=50)),
                (
                    "datRegSetac",
                    models.DateField(blank=True, db_column="datRegSetac", null=True),
                ),
                (
                    "idClanarine",
                    models.BigIntegerField(
                        blank=True, db_column="idClanarine", null=True
                    ),
                ),
                (
                    "idProfilne",
                    models.BigIntegerField(
                        blank=True, db_column="idProfilne", null=True
                    ),
                ),
            ],
            options={
                "db_table": '"Setac"',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Vlasnik",
            fields=[
                (
                    "idVlasnik",
                    models.BigAutoField(
                        db_column="idVlasnik", primary_key=True, serialize=False
                    ),
                ),
                (
                    "emailVlasnik",
                    models.CharField(db_column="emailVlasnik", max_length=50),
                ),
                (
                    "telefonVlasnik",
                    models.CharField(
                        blank=True, db_column="telefonVlasnik", max_length=15, null=True
                    ),
                ),
                (
                    "idPretplate",
                    models.BigIntegerField(
                        blank=True, db_column="idPretplate", null=True
                    ),
                ),
                (
                    "imeVlasnik",
                    models.CharField(
                        blank=True, db_column="imeVlasnik", max_length=20, null=True
                    ),
                ),
                (
                    "prezimeVlasnik",
                    models.CharField(
                        blank=True, db_column="prezimeVlasnik", max_length=20, null=True
                    ),
                ),
            ],
            options={
                "db_table": '"Vlasnik"',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_walker", models.BooleanField(default=False)),
                ("has_notifications_on", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
