# Generated by Django 5.1.2 on 2026-01-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_has_notifications_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlasnik',
            fields=[
                ('idVlasnik', models.BigAutoField(db_column='idVlasnik', primary_key=True, serialize=False)),
                ('emailVlasnik', models.CharField(db_column='emailVlasnik', max_length=50)),
                ('telefonVlasnik', models.CharField(blank=True, db_column='telefonVlasnik', max_length=15, null=True)),
                ('idPretplate', models.BigIntegerField(blank=True, db_column='idPretplate', null=True)),
                ('imeVlasnik', models.CharField(blank=True, db_column='imeVlasnik', max_length=20, null=True)),
                ('prezimeVlasnik', models.CharField(blank=True, db_column='prezimeVlasnik', max_length=20, null=True)),
            ],
            options={
                'db_table': '"Vlasnik"',
                'managed': False,
            },
        ),
    ]
