# Generated by Django 5.1.2 on 2026-01-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='setac',
            name='gradSetac',
            field=models.CharField(blank=True, db_column='gradSetac', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default=''),
        ),
    ]
