# Generated by Django 5.1.2 on 2026-01-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vlasnik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setac',
            fields=[
                ('idSetac', models.BigAutoField(db_column='idSetac', primary_key=True, serialize=False)),
                ('avgOcjena', models.DecimalField(blank=True, db_column='avgOcjena', decimal_places=2, max_digits=3, null=True)),
                ('imeSetac', models.CharField(blank=True, db_column='imeSetac', max_length=20, null=True)),
                ('prezimeSetac', models.CharField(blank=True, db_column='prezimeSetac', max_length=20, null=True)),
                ('telefonSetac', models.CharField(blank=True, db_column='telefonSetac', max_length=15, null=True)),
                ('usernameSetac', models.CharField(db_column='usernameSetac', max_length=20)),
                ('emailSetac', models.CharField(db_column='emailSetac', max_length=50)),
                ('datRegSetac', models.DateField(blank=True, db_column='datRegSetac', null=True)),
                ('idClanarine', models.BigIntegerField(blank=True, db_column='idClanarine', null=True)),
                ('idProfilne', models.BigIntegerField(blank=True, db_column='idProfilne', null=True)),
            ],
            options={
                'db_table': '"Setac"',
                'managed': False,
            },
        ),
    ]
