# Generated by Django 5.1.2 on 2026-01-20 17:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recenzija',
            fields=[
                ('idRecenzije', models.AutoField(primary_key=True, serialize=False)),
                ('ocjena', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('idSetac', models.ForeignKey(db_column='idSetac', on_delete=django.db.models.deletion.CASCADE, to='accounts.setac')),
                ('idVlasnik', models.ForeignKey(db_column='idVlasnik', on_delete=django.db.models.deletion.CASCADE, to='accounts.vlasnik')),
            ],
            options={
                'db_table': 'Recenzija',
            },
        ),
    ]
