# Generated by Django 5.1.2 on 2026-01-20 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlacanjeSetnje',
            fields=[
                ('idPlacanja', models.BigAutoField(db_column='idPlacanja', primary_key=True, serialize=False)),
                ('tipPlacanja', models.BigIntegerField(db_column='tipPlacanja')),
                ('cijenaSetnje', models.BigIntegerField(db_column='cijenaSetnje')),
                ('idRezervacije', models.BigIntegerField(db_column='idRezervacije')),
                ('idVlasnik', models.BigIntegerField(db_column='idVlasnik')),
                ('idSetac', models.BigIntegerField(db_column='idSetac')),
            ],
            options={
                'db_table': 'PlacanjeSetnje',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaymentTracking',
            fields=[
                ('payment', models.OneToOneField(db_column='idPlacanja', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tracking', serialize=False, to='payments.placanjesetnje')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_tracking',
            },
        ),
    ]
