# Generated by Django 5.1.2 on 2026-01-23 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placanjesetnje',
            options={'managed': False},
        ),
    ]
