# Generated by Django 5.1.2 on 2026-01-23 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_placanjesetnje_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='placanjesetnje',
            table='"PlacanjeSetnje"',
        ),
    ]
